### ISSUE TITLE
Add margin at the end of main view

### ISSUE THREAD

**Issue by kernelb00t** [sanoojes/better-bloom#1]
![image](https://github.com/sanoojes/better-bloom/assets/68474172/8e801060-7d49-41a8-b6c5-a91e187cf0f3)

> Where's my 30th song!? 

Debug Info (applicable for #1 #2 #3 #4 #5):
- ```  
  1 aur/spotify 1:1.2.31.1205-2 (+151 14.08) (Installed)
    A proprietary music streaming service
  ```
- Theme commit f3afe77
- Spicetify v2.36.11

**Comment by kernelb00t** [comment]
![image](https://github.com/sanoojes/better-bloom/assets/68474172/8976e58f-fa73-4f6f-ac72-9ca519e37302)

**Comment by kernelb00t** [comment]
![image](https://github.com/sanoojes/better-bloom/assets/68474172/d4cbf07d-1742-46d7-b042-7a4867a27555)

**Comment by kernelb00t** [comment]
![image](https://github.com/sanoojes/better-bloom/assets/68474172/ae5a3377-07bc-4e5b-a0ed-32bbde117dc8)

**Comment by sanoojes** [comment]
Thank you for submitting these issues! I've reviewed each one and appreciate the detail you've provided. 
I look forward to resolve these as efficiently as possible.
