### ISSUE TITLE
buttons like hitting web playing now and search

### ISSUE THREAD

**Issue by GildasEdraE** [sanoojes/better-bloom#10]
![Screenshot (124)](https://github.com/sanoojes/better-bloom/assets/89395504/3b3d4197-79dc-44d7-a5b9-cca3989b1d91)
I don't know what happened

**Comment by sanoojes** [comment]
it might be some issue with the plugins used can you provide your app info

**Comment by GildasEdraE** [comment]
> it might be some issue with the plugins used can you provide your app info
> 
> tried to add -webkit-mask for mask-image compatibility some times it should help

how I provide app info?
