### ISSUE TITLE
Text clipping in the searchbox

### ISSUE THREAD

**Issue by kamez104** [sanoojes/better-bloom#11]
### Do you have the latest versions of Spicetify, Spotify and Better Bloom?

- [X] I'm using the latest versions of Spicetify, Spotify and Better Bloom

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Is your problem definitely caused by the theme?

- [X] I have checked the app behavior without the theme and it is different

### Environment & Computer Info

```Markdown
- Spotify version: Spotify for Windows (64 bit) 1.2.37.701.ge66eb7bc
- Installed from: Spotify website
- Spicetify version: Spicetify v2.36.11
- Color scheme: dark
- Extensions: adblockify, Better Spotify Genres
- Custom apps: marketplace
- Better Bloom installation method: manual
```

### Description

When the searchbox is empty, the "What do you want to play?" text and the magnifying lens icon are cut off. The text is normal when there is text in the searchbox, but the magnifying lens icon is still cut off. I think the searchbox is also off-center too.
![image](https://github.com/sanoojes/better-bloom/assets/138945522/9b401777-c525-4b22-9708-7fa1244c0880)
![image](https://github.com/sanoojes/better-bloom/assets/138945522/07af5cdf-bc4c-4d67-96ef-a6f573c9895d)
![image](https://github.com/sanoojes/better-bloom/assets/138945522/06617aab-8c44-4ccc-9dc8-8f80d98975ca)
In newer versions of Spotify there is a new variant of the searchbox that's enabled by default, maybe you could use that one instead, but that's more of a suggestion. It and another variant can be enabled by changing the "Show global nav bar with home
button, search input and user avatar" setting in Experimental Features:
![image](https://github.com/sanoojes/better-bloom/assets/138945522/1fda6030-1729-4b45-bc73-20ed29173527)

**Comment by sanoojes** [comment]
ohh thanks !. 
am working on a fix now i will try to solve the issue as soon as possible the global nav with home is not supported by the theme yet i will make a fix for it also

**Comment by kamez104** [comment]
Neat, I appreciate you working on resolving these issues so fast 🫂

**Comment by sanoojes** [comment]
You're welcome! Glad I could help.

**Comment by sanoojes** [comment]
How is it looking ? 
do any adjustments needed?

![image](https://github.com/sanoojes/better-bloom/assets/93819264/807354d9-6c0e-47fe-bc76-2c847640aac3)

**Comment by kamez104** [comment]
Hmm, I feel like the global nav with home's searchbox should be a rounded rectangle like the one in Windows 11's File Explorer. You didn't show the original small searchbox though

**Comment by sanoojes** [comment]
yess i will make it like that !

**Comment by sanoojes** [comment]
updated the theme now
