### ISSUE TITLE
pause and play button

### ISSUE THREAD

**Issue by elijahmary** [sanoojes/better-bloom#12]
### Do you have the latest versions of Spicetify, Spotify and Better Bloom?

- [X] I'm using the latest versions of Spicetify, Spotify and Better Bloom

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Is your problem definitely caused by the theme?

- [X] I have checked the app behavior without the theme and it is different

### Environment & Computer Info

```Markdown
- Spotify version: 1.2.37.701.ge66eb7bc
- Installed from: offical exe file 
- Spicetify version: v2.36.11
- Color scheme: dark bloom
- Extensions:Beatiful Lyrics
- Custom apps: none
- Better Bloom installation method: Spicetify Marketplace
```

### Description

In any playlists stop/play button near songs (in both compact and list ) doesn't have proper scaling

### Screenshots

![image](https://github.com/sanoojes/better-bloom/assets/138471175/dd741c3b-d2f9-48ca-a50d-397f4d460ef1)
![image](https://github.com/sanoojes/better-bloom/assets/138471175/1265ac8e-f953-4154-b6d5-b3ed770e7579)

**Comment by sanoojes** [comment]
ohh my bad didnt even see those. sorry for the issue i will provide a fix rn !

**Comment by sanoojes** [comment]
the issue should be solved rn !
