### ISSUE TITLE
Lyrics button missing

### ISSUE THREAD

**Issue by tr330p** [sanoojes/better-bloom#14]
### Do you have the latest versions of Spicetify, Spotify and Better Bloom?

- [X] I'm using the latest versions of Spicetify, Spotify and Better Bloom

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Is your problem definitely caused by the theme?

- [x] I have checked the app behavior without the theme and it is different

### Environment & Computer Info

```Markdown
- Spotify version: Spotify for Windows (64 bit) 1.2.38.720.ga4a70a0e
- Installed from: Spotify site
- Spicetify version: v2.36.11
- Color scheme: idk
- Extensions: Beautiful Lyrics, Simple Beautiful Lyrics
- Custom apps: idk maybe nothing
- Better Bloom installation method: Spicetify Marketplace
```

### Description

The normal lyrics button in Spotify is gone! This happened after I installed your theme. I've tried reinstalling Spotify and Spicetify  completely, but the button only disappears when your theme is active. Sometimes I want to see the regular Spotify lyrics, not just the ones from the Beautiful Lyrics plugin. (Remove Beautiful Lyrics plugin is revert normal Spotify lyrics button but I want to have 2 lyrics button at the same time)

### Screenshots

![image](https://github.com/sanoojes/better-bloom/assets/170853932/e6adff08-4e7c-48ca-8ff3-48525962479d)

**Comment by sanoojes** [comment]
it was indented. when using beautiful lyrics extension the original lyrics button gets hidden as to avoid having 2 mic buttons

**Comment by sanoojes** [comment]
i will bring back the button when using beautiful lyrics now!

**Comment by sanoojes** [comment]
![image](https://github.com/sanoojes/better-bloom/assets/93819264/aa5910e5-4c28-4840-b08e-0f8650403692)
