### ISSUE TITLE
After adding a song to a playlist the notification is not showing

### ISSUE THREAD

**Issue by BedBug2479** [sanoojes/better-bloom#16]
### Do you have the latest versions of Spicetify, Spotify and Better Bloom?

- [X] I'm using the latest versions of Spicetify, Spotify and Better Bloom

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Is your problem definitely caused by the theme?

- [X] I have checked the app behavior without the theme and it is different

### Environment & Computer Info

```Markdown
Spotify version: 1.2.38.720.ga4a70a0e
- Installed from: (Windows Store, Spotify site, Flatpak, etc) Spotify Site
- Spicetify version:v2.36.11
- Color scheme: Dark
- Bloom installation method: (Spicetify Marketplace/PowerShell script/Bash script/Manual) Marketplace
```

### Description

When i add a song to a playlist the notification is unreadable

### Screenshots

![image](https://github.com/sanoojes/better-bloom/assets/43089040/6277848a-3ba6-491f-994f-67ccaa31e457)

**Comment by BedBug2479** [comment]
it seems like no notification is visible; i tried changing shuffle on and off that also not visible

![image](https://github.com/sanoojes/better-bloom/assets/43089040/d267a2a8-9507-4c09-a644-513f6bfa226e)

**Comment by sanoojes** [comment]
oops soory for the inconvenence ! 
i will checkout that issue and fix it rn !
