### ISSUE TITLE
remove the borders for a better visual

### ISSUE THREAD

**Issue by BedBug2479** [sanoojes/better-bloom#17]
Is it possible to remove the lines/borders present in each frame of spotify

![image](https://github.com/sanoojes/better-bloom/assets/43089040/a46e93f5-92b5-41f6-926f-61b0417c4ce0)

**Comment by sanoojes** [comment]
yes you can by adding this snippet :root {--default-border-thickness: 0px;}

i think its better to have borders for it

**Comment by sanoojes** [comment]
or should i decrese the borders to 1px 
![image](https://github.com/sanoojes/better-bloom/assets/93819264/05197f9b-9c67-419d-8caf-a53c12ec814b)

**Comment by BedBug2479** [comment]
> or should i decrese the borders to 1px ![image](https://private-user-images.githubusercontent.com/93819264/335073521-05197f9b-9c67-419d-8caf-a53c12ec814b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcwNTI2NjMsIm5iZiI6MTcxNzA1MjM2MywicGF0aCI6Ii85MzgxOTI2NC8zMzUwNzM1MjEtMDUxOTdmOWItOWM2Ny00MTlkLThjYWYtYTUzYzEyZWM4MTRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMwVDA2NTkyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJhOWVjNzM0YmI2MGJhYjU5Y2NiNWIzNGNjZjk0ZWE4NjhlZGExOGQyZDk0YzZkMDFmOGY1YWM2MmI0NDY2MzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oGozlSFkUNiXH5wkkYIyPY02LWZ1MnXgfLExgpp_RRk)

yep 1px looks better

**Comment by BedBug2479** [comment]
else if possible allow a borderless theme only if not too much work



> yes you can by adding this snippet :root {--default-border-thickness: 0px;}
> 
> i think its better to have borders for it
> 
> without borders. ![image](https://private-user-images.githubusercontent.com/93819264/335073045-c7c79539-9148-4ed5-9c72-7eebcf1e2032.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcwNTI2NjMsIm5iZiI6MTcxNzA1MjM2MywicGF0aCI6Ii85MzgxOTI2NC8zMzUwNzMwNDUtYzdjNzk1MzktOTE0OC00ZWQ1LTljNzItN2VlYmNmMWUyMDMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMwVDA2NTkyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFhOTc3NDg3Y2MwN2Y3NjBkNTY0OWQ3NGYwNjQwODNlZDc2YWZlZWE1MDNkYWIwNmZhNDQzMjAzNjBhMzM2NjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qTetH_YZelDQPeeOOpdaup-UQghrhdq06OZW6M8CsRo)

for now i will add this and switch to 1px when updated

**Comment by sanoojes** [comment]
its updated now ! https://github.com/sanoojes/better-bloom/commit/9cc9e33940747c2e9e1237e40bf606642b366932

**Comment by sanoojes** [comment]
i will add customization features for the theme soon
