### ISSUE TITLE
Eternal Jukebox button doesn't show

### ISSUE THREAD

**Issue by polyjitter** [sanoojes/better-bloom#18]
### Do you have the latest versions of Spicetify, Spotify and Better Bloom?

- [X] I'm using the latest versions of Spicetify, Spotify and Better Bloom

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Is your problem definitely caused by the theme?

- [X] I have checked the app behavior without the theme and it is different

### Environment & Computer Info

```Markdown
- Spotify version: 1.2.38.720.ga4a70a0e
- Installed from: Spotify site
- Spicetify version: v2.36.11
- Color scheme: Any
- Extensions: Cover Ambience, Volume+, Scannables
- Custom apps: Eternal Jukebox, Marketplace
- Better Bloom installation method: Spicetify Marketplace
```

### Description

When using the Eternal Jukebox custom app, the button to enable the jukebox does not show.

### Screenshots

![image](https://github.com/sanoojes/better-bloom/assets/18127936/876e9c17-14dd-43a2-9540-02835aa4c2a1)
![image](https://github.com/sanoojes/better-bloom/assets/18127936/89821023-c29f-4484-a63d-6755fe92a51d)

**Comment by sanoojes** [comment]
i will tryout the eternal jukebox app and try to fix it i think it overwrites the playbar css which would cause issue sometimes

**Comment by sanoojes** [comment]
The issue seems to be that the theme is removing the SVG for the repeat button, which is essential for the jukebox's infinity button functionality. i will make it specific for the repeat button rn !

**Comment by sanoojes** [comment]
also should i change the infintiy icon to 
![image](https://github.com/sanoojes/better-bloom/assets/93819264/dc6febbb-3b15-4323-bfab-c7e585818206)

from 
![image](https://github.com/sanoojes/better-bloom/assets/93819264/faf45941-fc1a-4506-82ac-aaae296e28d9)
