### ISSUE TITLE
[Bug] Overflowing section in liked songs playlist

### ISSUE THREAD

**Issue by ShadowMonster99** [sanoojes/better-bloom#19]
### Do you have the latest versions of Spicetify, Spotify and Better Bloom?

- [X] I'm using the latest versions of Spicetify, Spotify and Better Bloom

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Is your problem definitely caused by the theme?

- [X] I have checked the app behavior without the theme and it is different

### Environment & Computer Info

```Markdown
Spotify for Windows (64 bit)
1.2.38.720.ga4a70a0e
Spicetify v2.36.11
Theme: Better-Bloom / dark
Extensions: theme.js
Custom apps: marketplace
```

### Description

1. Go to liked songs playlist
2. See the overflowing area where the play button and tags rest; right below the album cover

### Screenshots

![image](https://github.com/sanoojes/better-bloom/assets/81448108/b89c7495-0ee2-442f-adf9-a26e16e246c3)

**Comment by sanoojes** [comment]
sorry for the issue caused i will fix it as soon as possible

**Comment by sanoojes** [comment]
updated the theme !.
as am not able to reproduce the issue i tried a fix for it hope it helps 
checkout the theme now is the issue fixed ?

**Comment by ShadowMonster99** [comment]
Works great now! Thanks.

**Comment by sanoojes** [comment]
Awesome ! thanks for using the theme

**Comment by ShadowMonster99** [comment]
commit 19f9ba4fd7b33fee7f3d452befbf758444b146e5 breaks this fix

**Comment by sanoojes** [comment]
ohh soory for the issue caused i did it by mistake
