### ISSUE TITLE
There is a gap when zooming out

### ISSUE THREAD

**Issue by GildasEdraE** [sanoojes/better-bloom#20]
![IMG_20240602_003747](https://github.com/sanoojes/better-bloom/assets/89395504/76569b14-a127-42bf-b76b-5c414585fa86)
This is a spicetify appearance with better bloom but default zoom, I don't like that.

![IMG_20240602_001942](https://github.com/sanoojes/better-bloom/assets/89395504/93331d61-c297-4834-82f9-fbf6bcb5a5d5)
When Zooming out, a gap appeared near windows control(with control global nav).

![IMG_20240602_002017](https://github.com/sanoojes/better-bloom/assets/89395504/eec5ac9c-3dec-4b8d-b8c5-92ea93508878)
And this is when use home-to-next-search/navigation(global nav) the profile is hitting windows control.

**Comment by sanoojes** [comment]
oo i will fix that soon
