### ISSUE TITLE
Play/resume and loop buttons broken after latest update

### ISSUE THREAD

**Issue by kamez104** [sanoojes/better-bloom#21]
### Do you have the latest versions of Spicetify, Spotify and Better Bloom?

- [X] I'm using the latest versions of Spicetify, Spotify and Better Bloom

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Is your problem definitely caused by the theme?

- [X] I have checked the app behavior without the theme and it is different

### Environment & Computer Info

```Markdown
- Spotify version: Spotify for Windows (64-bit) 1.2.38.720.ga4a70a0e
- Installed from: Spotify site
- Spicetify version: Spicetify v2.36.12
- Color scheme: dark
- Extensions: adblockify
- Custom apps: marketplace
- Better Bloom installation method: issue happens when better-bloom is installed through Marketplace and Github
```

### Description

.

### Screenshots

![image](https://github.com/sanoojes/better-bloom/assets/138945522/57b11420-cae8-4b27-bc05-3884b2ce639e)

**Comment by sanoojes** [comment]
sorry that broke some things i will revert it

**Comment by sanoojes** [comment]
reverted the comit [6034cd7](https://github.com/sanoojes/better-bloom/commit/6034cd7a6d92a5d0801c5d5999e9ab061ae7c5a1) can you check if it is working

**Comment by sanoojes** [comment]
@kamez104 did it work

**Comment by sanoojes** [comment]
is it fixed ? @kamez104

**Comment by kamez104** [comment]
Yes, the issue is fixed now
