### ISSUE TITLE
Searchbar visual bugs 

### ISSUE THREAD

**Issue by kamez104** [sanoojes/better-bloom#22]
### Do you have the latest versions of Spicetify, Spotify and Better Bloom?

- [X] I'm using the latest versions of Spicetify, Spotify and Better Bloom

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Is your problem definitely caused by the theme?

- [X] I have checked the app behavior without the theme and it is different

### Environment & Computer Info

```Markdown
- Spotify version: Spotify for Windows (64-bit) 1.2.38.720.ga4a70a0e
- Installed from: Spotify site
- Spicetify version: Spicetify v2.36.12
- Color scheme: dark
- Extensions: adblockify
- Custom apps: marketplace
- Better Bloom installation method: issue happens when better-bloom is installed through Marketplace and Github
```

### Description

1. When typing, a circle appears around the “x” button
![image](https://github.com/sanoojes/better-bloom/assets/138945522/6fe38eb1-2804-41bf-831f-4f27911eb2ae)
2. When clicked, the “Browse” button becomes a white square
![image](https://github.com/sanoojes/better-bloom/assets/138945522/e0cf4e25-1e2d-40d8-bb6c-5c8a65d27eab)

**Comment by sanoojes** [comment]
soory for the issue caused i cant reproduce the issue i will try to fix it soon
![Uploading image.png…]()

**Comment by sanoojes** [comment]
found out the issue it was locale specific for English i will make it compatible with all languages
