### ISSUE TITLE
[Not sure if bug] Icons are now in square shape

### ISSUE THREAD

**Issue by BedBug2479** [sanoojes/better-bloom#23]
### Do you have the latest versions of Spicetify, Spotify and Better Bloom?

- [X] I'm using the latest versions of Spicetify, Spotify and Better Bloom

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Is your problem definitely caused by the theme?

- [X] I have checked the app behavior without the theme and it is different

### Environment & Computer Info

```Markdown
- Spotify version: 1.2.38.720.ga4a70a0e
- Installed from: (Windows Store, Spotify site, Flatpak, etc) Spotify Site
- Spicetify version:v2.36.12
- Color scheme: Dark
- Bloom installation method: (Spicetify Marketplace/PowerShell script/Bash script/Manual) Marketplace
```

### Description

after the spicetify update the icons are now in square format

has the UI been changed?

### Screenshots

![image](https://github.com/sanoojes/better-bloom/assets/43089040/8e0b1ee3-0f1f-4ad6-b61f-ccf6d8540a1a)

**Comment by sanoojes** [comment]
soory that was an issue with my code totaly forgot to add semicolon 🙂 
fixed it
https://github.com/sanoojes/better-bloom/commit/2ba95dcca35691736376ec18c25c2e844b07d987

**Comment by sanoojes** [comment]
@BedBug2479  the new buttons are not circle as the fluent theme consists of rounded square circles you can always get back the circle buttons by adding this snippet 

```css
:root{ --button-border-radius: 999px; }
```
