### ISSUE TITLE
Now Playing bar covers the buttons of the lyrics plus

### ISSUE THREAD

**Issue by GildasEdraE** [sanoojes/better-bloom#24]
![Screenshot (161)](https://github.com/sanoojes/better-bloom/assets/89395504/4a9afc3e-051a-42f8-b28e-7b1ab0c5f904)

If closer
![Screenshot (162)](https://github.com/sanoojes/better-bloom/assets/89395504/41678067-8fd7-4d03-9030-383e928c9436)

**Comment by sanoojes** [comment]
sorry for causing the issue i will check lyrics plus extension and fix it

**Comment by sanoojes** [comment]
fixed it rn ! check if it is working
