### ISSUE TITLE
High cpu load and significant lags when scrolling thru playlists

### ISSUE THREAD

**Issue by Blagene** [sanoojes/better-bloom#26]
### Do you have the latest versions of Spicetify, Spotify and Better Bloom?

- [X] I'm using the latest versions of Spicetify, Spotify and Better Bloom

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Is your problem definitely caused by the theme?

- [X] I have checked the app behavior without the theme and it is different

### Environment & Computer Info

```Markdown
- Spotify version: 1.2.38.720 
- Installed from: Spotify site
- Spicetify version: v2.36.12
- Color scheme: dark
- Extensions: 
- Custom apps:
- Better Bloom installation method: Spicetify Marketplace/PowerShell script
```

### Description

1. faced significant lags while using this theme
2. tried another one and everything worked well
3. reinstalled spicetify
4. tried the theme alone with stock spicetify
5. still laggy

**Comment by sanoojes** [comment]
soory for the issue caused i will investigate the issue and fix the issue as soon as possible

**Comment by sanoojes** [comment]
soory for the issue caused i will figure a way to reduse lag

**Comment by sanoojes** [comment]
i will add some tweaks in css but the CPU usage will be sometimes same as before as Spotify utilizes the CPU for the scrolling in playlist. 


### Bloom after tweeks
https://github.com/sanoojes/better-bloom/assets/93819264/778498f0-e7e9-4d7e-809f-f03c604ea8d5

### Normal spotify without any theme 
https://github.com/sanoojes/better-bloom/assets/93819264/198ce2c7-0df2-4db4-ae28-8abd28b31fac

**Comment by Blagene** [comment]
I really appreciate your help, your theme looks the best from the ones I found on the marketplace. I will try the new version ASAP. I was checking the CPU usage of Spotify itself and it does take quite a bit even without Spicetify or your Bloom theme. Especially when it comes to scrolling playlists.

**Comment by sanoojes** [comment]
yes it is. scrolling in Spotify eats a lot of CPU
