### ISSUE TITLE
Reversed next and last track buttons.

### ISSUE THREAD

**Issue by Ergoprett** [sanoojes/better-bloom#27]
### Do you have the latest versions of Spicetify, Spotify and Better Bloom?

- [X] I'm using the latest versions of Spicetify, Spotify and Better Bloom

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Is your problem definitely caused by the theme?

- [X] I have checked the app behavior without the theme and it is different

### Environment & Computer Info

```Markdown
- Spotify version: 1.2.39.578.g0ea3f38b
- Installed from: Spotify site
- Spicetify version: v2.36.12
- Color scheme: dark
- Extensions: Full Screen, Bookmark, Volume Percentage, Display full Album date, Cover Ambience, Quick Queue, NPV Ambience, Old Like Button
- Custom apps: Name That Tune, 
- Better Bloom installation method: Spicetify Marketplace
```

### Description

I just installed this theme, which looks very nice. 
But every time, the next and last track buttons are reversed.

### Screenshots

![image](https://github.com/sanoojes/better-bloom/assets/87259731/fb1d5eaf-a56d-41f5-9e35-28de460cf8ca)

**Comment by sanoojes** [comment]
sorry for the issue caused i will fix it rn ! it was a mistake by me
