### ISSUE TITLE
Animated Background like Beautiful Lyrics

### ISSUE THREAD

**Issue by yuma-dev** [sanoojes/better-bloom#28]
**Is your feature request related to a problem? Please describe.**
No, not at all

**Describe the solution you'd like**
First of all, I would love compatibility with Beautiful Lyrics' "Current Title" view. Currently, the dynamic animated background is fully opaque while other elements are more hidden. This isn't a huge problem, though.

However, my main idea is that the animated background could be used as the background for the entire app. I’m not sure if this is possible with just a theme or if it’s possible because it’s an extension. 
If it’s not possible, maybe you could include the dynamic background from the extension?

**Describe alternatives you've considered**
Not include this idea, no biggie ^^

**Additional context**
A Gif of what I am talking about (ignore the glitches):
![Spotify_MT3s2qViDn](https://github.com/sanoojes/better-bloom/assets/76885566/0625a40b-346d-4f7e-9d83-0f89c268e385)

**Comment by sanoojes** [comment]
yes we can use that for the whole background of the app i will add a customization feature for that soon. also i will decrease the bg opacity which would make it nice 

now: 
![image](https://github.com/sanoojes/better-bloom/assets/93819264/01d54aa7-a332-41e3-b62d-2973056981dd)

opacity 0.5
![image](https://github.com/sanoojes/better-bloom/assets/93819264/7200b360-f895-4182-aca0-f3dfc69bdbcf)

**Comment by sanoojes** [comment]
should i add transperency to it 
and the requested feature will be added soon as i can !

**Comment by yuma-dev** [comment]
awesome thank you so much! and yes a customization option for that would be neat

much love!

**Comment by sanoojes** [comment]
yes it looks better on the theme ! am adding that right now !

opacity 1
![image](https://github.com/sanoojes/better-bloom/assets/93819264/115f1e14-b687-400a-9fa8-844031471458)

opacity 0.5
![image](https://github.com/sanoojes/better-bloom/assets/93819264/84684f56-92f2-46ec-8c98-5fcbc8dc640f)

**Comment by sanoojes** [comment]
also added features for customizations !

**Comment by sanoojes** [comment]
check new update https://github.com/sanoojes/better-bloom/commit/e9209fc6e0db27d9b7339ac875cb913abd24a522

added the animated bg you can toggle it in bloom settings

**Comment by yuma-dev** [comment]
Looks absolutely stunning, thank you so much!

**Comment by sanoojes** [comment]
welcome and thanks for using the theme🥰
am closing this issue rn

**Comment by yuma-dev** [comment]
ah but it seems to have caused a new bug:
![image](https://github.com/sanoojes/better-bloom/assets/76885566/b363f2c9-9532-46b5-a921-c643041ed8ca)

**Comment by sanoojes** [comment]
ohh i think its because of the spicetify version or spotify version can you try updating them

**Comment by yuma-dev** [comment]
both spotify and spicetify are running on the newest version (spicetify v2.36.12 and spotify doesn't have any updates for me)

**Comment by yuma-dev** [comment]
ah oops you already replied, no problem!

**Comment by sanoojes** [comment]
fixed the issue the theme should be updated in several minutes

**Comment by yuma-dev** [comment]
that only seems to fix it on smaller windows, if i have spotify maximized it looks like this:
![image](https://github.com/sanoojes/better-bloom/assets/76885566/25f32d17-d252-4740-a1cb-e246d268670c)

also it seems like the size of the grabbable window frame is too small, i often am unable to find where i can grab the title bar

**Comment by sanoojes** [comment]
i tried on different screen sizes and i cant replicate the issue can is any extensions modifying the top bar ?
can you give the extensions or custom apps used 
![image](https://github.com/sanoojes/better-bloom/assets/93819264/23c2815a-01c9-4962-9b10-c9b7578197c7)
![image](https://github.com/sanoojes/better-bloom/assets/93819264/56c81797-f405-40bc-81bb-88efb1fdddbb)
![image](https://github.com/sanoojes/better-bloom/assets/93819264/063ac6b8-1979-4dbd-be6b-0f6b77cde6d5)

**Comment by yuma-dev** [comment]
![image](https://github.com/sanoojes/better-bloom/assets/76885566/15a01120-4181-42a7-b4a3-f775656e269c)
happens only on my 4k monitor if i maximize spotify

also only this top left area seems to be draggable:
![image](https://github.com/sanoojes/better-bloom/assets/76885566/b628144f-73cd-486a-928f-017a07f0d325)

sorry for the late answer!

**Comment by sanoojes** [comment]
no probs i will fix the draggable area rn ! and i think the card will be like that

**Comment by sanoojes** [comment]
@yuma-dev is the controls transparent in the 4k displays 
![image](https://github.com/sanoojes/better-bloom/assets/93819264/fd494fc0-906d-4d68-a6b6-89ba997d69a6)
like this

**Comment by yuma-dev** [comment]
![image](https://github.com/sanoojes/better-bloom/assets/76885566/3383d420-fcac-4ca8-89ef-7396a43ecda6)
seems like it

**Comment by sanoojes** [comment]
i got a fix for this i will implement it soon is the playlist view like this 
![image](https://github.com/sanoojes/better-bloom/assets/93819264/403aa6c4-e1ac-4450-8a87-52debbfe29da)

**Comment by yuma-dev** [comment]
![image](https://github.com/sanoojes/better-bloom/assets/76885566/bf4b4255-ef85-4a9a-b675-8c63c453e8e2)
i dont think so

**Comment by sanoojes** [comment]
ohh good then it just to confirm my test setup is good or not soory for the delay i will fix it rn

**Comment by yuma-dev** [comment]
absolutely no problem, these don't bother me at all
also, I noticed the playlist banner/icon not being centered
![image](https://github.com/sanoojes/better-bloom/assets/76885566/d675aea5-18c8-4479-b864-ca757a0e4f6e)

**Comment by sanoojes** [comment]
thanks for replaying
