### ISSUE TITLE
Whenever using the script I get an error that says "Spotify isn't installed"

### ISSUE THREAD

**Issue by HuangLinBao** [sanoojes/better-bloom#29]
### Do you have the latest versions of Spicetify, Spotify and Better Bloom?

- [X] I'm using the latest versions of Spicetify, Spotify and Better Bloom

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Is your problem definitely caused by the theme?

- [X] I have checked the app behavior without the theme and it is different

### Environment & Computer Info

```Markdown
- Spotify version: 1.2.37.701
- Installed from: flatpak
- Spicetify version: 2.36.8
- Color scheme:
- Extensions:
- Custom apps:
- Better Bloom installation method: Bash Script
```

### Description

Whenever I run the installation script I get this error:
`Spotify isn't installed or doesn't exist in your PATH.
Better-Bloom is a Spotify theme, and so it's essential.
Please install Spotify (https://spotify.com/download) and run this script again to continue.
If Spotify is already installed, add it to your PATH variable and rerun this script.
Example command for adding to PATH: export PATH=~/spotify:$PATH
Abort!`

I tried installing other themes and it worked fine. this one however, it didn't work. Also, I tried adding spotify to $PATH but no use.

### Screenshots

![image](https://github.com/sanoojes/better-bloom/assets/57255961/2de8a32c-ed5c-45d2-8cd4-22c168e2e894)

**Comment by sanoojes** [comment]
i will check it on my linux vm and figure out the issue rn !

**Comment by sanoojes** [comment]
cant find the issue i will fix it as soon as possible

**Comment by sanoojes** [comment]
added new script can you check the script installation @HuangLinBao

**Comment by HuangLinBao** [comment]
It worked, Thank you so much
