### ISSUE TITLE
Blur is too strong

### ISSUE THREAD

**Issue by kernelb00t** [sanoojes/better-bloom#3]
The blur of elements on screen can be improved:
- 3rem of radius makes home's items "bleed" and blur with the adjacent colors. 1rem seems a bit better.
- The blur brightness of the right click menu is too bright: Original Spotify one is darker than the overall UI. Even Windows, Firefox, Discord, etc...  has it darker. 
![image](https://github.com/sanoojes/better-bloom/assets/68474172/b6d69403-8ccd-4fa3-b9af-ef49529966f8)
![image](https://github.com/sanoojes/better-bloom/assets/68474172/d447ec5a-5b92-4011-9556-df955007ed6a)

**Comment by kernelb00t** [comment]
The Context Menu problem only appears on the Home page and in main UI:

https://github.com/sanoojes/better-bloom/assets/68474172/068c1454-25bf-4c8d-81e3-52581f53f030

![image](https://github.com/sanoojes/better-bloom/assets/68474172/d13072ee-78de-4772-a2e1-039b5d2d7309)
![image](https://github.com/sanoojes/better-bloom/assets/68474172/ec096d19-6a6d-4df0-a887-b706ff4a6af2)
![Capture d’écran du 2024-05-12 10-11-41](https://github.com/sanoojes/better-bloom/assets/68474172/f09a8532-9371-4e2b-b2bc-2497187cbfa2)

**Comment by sanoojes** [comment]
ohh soory for that i reduced blur to 1.5rem also fixed the right click menu 
will push all the fixes for issues soon in next commit 

![image](https://github.com/sanoojes/better-bloom/assets/93819264/b3150f2e-5e09-44d9-9833-edf3546223ec)
![image](https://github.com/sanoojes/better-bloom/assets/93819264/4aa1833c-406a-4771-9391-c436c359c6a0)
![image](https://github.com/sanoojes/better-bloom/assets/93819264/d95cf96c-7337-47c2-805c-f49b22688a46)
![image](https://github.com/sanoojes/better-bloom/assets/93819264/d4558306-f7ef-41cb-b56e-eb0ca61c5599)

**Comment by sanoojes** [comment]
can you checkout the new commit
