### ISSUE TITLE
Is there a way to disable dynamic backgrounds?

### ISSUE THREAD

**Issue by adjaycents** [sanoojes/better-bloom#30]
I would prefer just [one] or [no] background image instead of it changing with the cover.

Also is there a way to make it less laggy while scrolling through playlists?

The theme is absolutely beautiful.

**Comment by sanoojes** [comment]
yes i will add feature to make the background solid color 

and scrolling through the playlist consumes cpu thats why its laggy its not the problem of the theme i think its something to do from spotify side

checkout #26 
https://github.com/sanoojes/better-bloom/issues/26#issuecomment-2149698163

**Comment by jaygaros** [comment]
That would be amazing thanks!

Noted @ scrolling. That's unfortunate.

**Comment by sanoojes** [comment]
check the update ! you can now select between background styles

![image](https://github.com/sanoojes/better-bloom/assets/93819264/f11ba2eb-f4bb-4496-9174-2147474cc80d)
