### ISSUE TITLE
Categories are missing in some custom apps when using global nav: home-to-next-seach/navigation

### ISSUE THREAD

**Issue by GildasEdraE** [sanoojes/better-bloom#31]
### Do you have the latest versions of Spicetify, Spotify and Better Bloom?

- [X] I'm using the latest versions of Spicetify, Spotify and Better Bloom

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Is your problem definitely caused by the theme?

- [X] I have checked the app behavior without the theme and it is different

### Environment & Computer Info

```Markdown
- Spotify version: 1.2.39.578.g0ea3f38b
- Installed from: Spotify site
- Spicetify version: 2.36.12
- Color scheme: dark
- Extensions:
- Custom apps: marketplace, new-releases, lyrics-plus, stats, library
- Better Bloom installation method: Spicetify Marketplace
```

### Description

1. categories missing in some custom apps when using global nav: home-to-next-seach/navigation
2. but when using global nav: control, there are categories, but they are at the top
3. in stats custom apps, categories does not missing, but it's just invisble 
4. and when I scrolling, there are categories

### Screenshots

I'am gonna mark that as yellow

,
![Screenshot (194)](https://github.com/sanoojes/better-bloom/assets/89395504/937919a5-49a9-4644-8d9c-59e25ad973ab)
sample: stats custom app when using global nav: control

,
![Screenshot (195)](https://github.com/sanoojes/better-bloom/assets/89395504/10ffb1cd-623e-41bf-aea7-bbd24648e41a)
lyrics-plus when using  global nav: control

,
![Screenshot (196)](https://github.com/sanoojes/better-bloom/assets/89395504/2900bdba-170b-435d-a285-04711bfc0ec3)
lyrics-plus when using global nav: home-to-next-seach/navigation

,
![Screenshot (197)](https://github.com/sanoojes/better-bloom/assets/89395504/4a2877d4-2ff0-4ba1-9c30-2a674cb52eb3)
stats when using global nav: home-to-next-seach/navigation

,
![Screenshot (198)](https://github.com/sanoojes/better-bloom/assets/89395504/f661aada-57c0-4255-a31a-e64db99063bf)
and when scrolling

**Comment by sanoojes** [comment]
sorry for the inconvenience ! i will check out this custom app and fix it
