### ISSUE TITLE
picture on artist page bugs when scrolling

### ISSUE THREAD

**Issue by GildasEdraE** [sanoojes/better-bloom#32]
### Do you have the latest versions of Spicetify, Spotify and Better Bloom?

- [X] I'm using the latest versions of Spicetify, Spotify and Better Bloom

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Is your problem definitely caused by the theme?

- [X] I have checked the app behavior without the theme and it is different

### Environment & Computer Info

```Markdown
- Spotify version: 1.2.39.578.g0ea3f38b
- Installed from: Spotify site
- Spicetify version: 2.36.12
- Color scheme:
- Extensions:
- Custom apps:
- Better Bloom installation method: Spicetify Marketplace
```

### Description

1. picture on artist page just like doesn't  move when scrolling

### Screenshots

![Screenshot (199)](https://github.com/sanoojes/better-bloom/assets/89395504/bcc296f7-6112-4ddc-bf1f-19d1e5a6dc12)
artist page when normal

![Screenshot (200)](https://github.com/sanoojes/better-bloom/assets/89395504/3fb2f32d-2553-4d21-864a-638307c2802f)
when scrolling

**Comment by sanoojes** [comment]
sorry for the issue caused i will address it rn ! it only works when scrolled slowly i will make a fix for it

**Comment by GildasEdraE** [comment]
> maaf atas masalah yang ditimbulkan, saya akan mengatasinya rn! ini hanya berfungsi ketika digulir perlahan saya akan memperbaikinya

Thank you so much
