### ISSUE TITLE
Theme not installing, showing errors (Powershell script)

### ISSUE THREAD

**Issue by ShyMaster202** [sanoojes/better-bloom#33]
### Do you have the latest versions of Spicetify, Spotify and Better Bloom?

- [X] I'm using the latest versions of Spicetify, Spotify and Better Bloom

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Is your problem definitely caused by the theme?

- [X] I have checked the app behavior without the theme and it is different

### Environment & Computer Info

```Markdown
- Spotify version: 1.2.40.592.gb83da72d
- Installed from: SpotX auto install script (Windows)
- Spicetify version: v2.36.12
- Color scheme: N/A
- Extensions: N/A
- Custom apps: N/A
- Better Bloom installation method: PowerShell script
```

### Description

1. Paste the install script for the theme into the terminal and run
2. Errors pop up
I'm assuming the errors are because my user folder has a space in it

### Screenshots

![image](https://github.com/sanoojes/better-bloom/assets/88460160/a2750c8f-c086-4552-bd25-f6ec3685dee7)

**Comment by sanoojes** [comment]
soory for the issue caused i will checkout the issue rn !

**Comment by sanoojes** [comment]
it think the space in user folder is the issue

**Comment by sanoojes** [comment]
@ShyMaster202 i cant reproduce this issue ! tried space in user folder name

**Comment by ShyMaster202** [comment]
wait now that i look at the error again it looks like its something to do with remove-item and move-item, not sure why though

**Comment by sanoojes** [comment]
yes your user name and username the script is trying to move is different idk why it is like that

**Comment by amd64fox** [comment]
> idk why it is like that

don't use `$env:TEMP`
use `[System.IO.Path]::GetTempPath()`

**Comment by sanoojes** [comment]
thanks i will add that !

**Comment by ShyMaster202** [comment]
![image](https://github.com/sanoojes/better-bloom/assets/88460160/5a7ce72d-822c-401a-bc4a-ec76e95c4517)
it presents this error, however the theme installed and is fully functional now! thank you both 👍

**Comment by amd64fox** [comment]
> it presents this error


I think this line should be removed, since the assignment to the $Temp variable inside the hash is an error, especially since it was declared above

https://github.com/sanoojes/better-bloom/blob/53dafdae8bbda74ae3e26cb9746c26d906eb2163/install/Functions.psm1#L302

**Comment by ShyMaster202** [comment]
works perfectly now!
