### ISSUE TITLE
Laggy UI and Animations acting after spotify ones(with delay). 

### ISSUE THREAD

**Issue by Nimai-HK** [sanoojes/better-bloom#35]
### Do you have the latest versions of Spicetify, Spotify and Better Bloom?

- [X] I'm using the latest versions of Spicetify, Spotify and Better Bloom

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Is your problem definitely caused by the theme?

- [X] I have checked the app behavior without the theme and it is different

### Environment & Computer Info

```Markdown
- Spotify version:
- Installed from: (Windows Store, Spotify site, Flatpak, etc)
- Spicetify version:
- Color scheme:
- Extensions:
- Custom apps:
- Better Bloom installation method: (Spicetify Marketplace/PowerShell script/Bash script/Manual)
```

### Description

Exactly what the title says.

1. The theme's animations act after Spotify's (after a delay). Makes the app lag for a moment (fix- change animation scale, make the animations themselves subtler. Reduce animated elements)

2.Extremely high cpu usage on lower end pc's.

3.When the theme fails to fetch song cover, it replaces backdrop to an orange one..(fix- replace with black backdrop instead)

4.UI borders are not prominent enough, accessibility issues. (fix- Increase or decrease darkness and blur values of different UI parts, Like sidebar, nowplaying, Buttons, etc)

5. Banner images don't load, leave behind a dotted (starry) background in it's place

By the way, AMAZING theme. Very few bugs. Beautiful bro.

**Comment by sanoojes** [comment]
soory for the issue i will fix the issues on lower end pcs am working on it i will add fixes and support fast !

**Comment by sanoojes** [comment]
Hey can you check out the theme rn ! i fixed all lag issues in v2 checkout !
