### ISSUE TITLE
upper UI

### ISSUE THREAD

**Issue by elijahmary** [sanoojes/better-bloom#38]
### Do you have the latest versions of Spicetify, Spotify and Better Bloom?

- [X] I'm using the latest versions of Spicetify, Spotify and Better Bloom

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Is your problem definitely caused by the theme?

- [X] I have checked the app behavior without the theme and it is different

### Environment & Computer Info

```Markdown
- Spotify version: 1.2.40.599.g606b7f29
- Installed from: Spotify site
- Spicetify version: v2.36.13
- Color scheme: dark
- Extensions:
- Custom apps:
- Better Bloom installation method: Spicetify Marketplace
```

### Description

upper UI on home and markeplace doesn't order so they all cramed into one line

### Screenshots

without better-bloom
![image](https://github.com/sanoojes/better-bloom/assets/138471175/b5f7251d-4893-4f81-a4d4-f90c5837207d)
with better-bloom
![image](https://github.com/sanoojes/better-bloom/assets/138471175/fdf6e611-5c81-49b7-8ae6-489e62e2627a)
marketplace
![image](https://github.com/sanoojes/better-bloom/assets/138471175/9b1e73f2-2f51-464a-841c-02438778a042)

**Comment by sanoojes** [comment]
yes it is buggy with the new spotify update i will address them in v2 release
