### ISSUE TITLE
Compatiblity: Full Screen Display with Beautiful Lyrics

### ISSUE THREAD

**Issue by kernelb00t** [sanoojes/better-bloom#4]
![image](https://github.com/sanoojes/better-bloom/assets/68474172/ec61ed4c-17bf-4a12-a836-1272dc311a52)
Album picture is obviously too small; fyi spicetify bloom gets it right

**Comment by sanoojes** [comment]
yes i put a max height of 56px on that one soory to cause a issue i will fix it in next commit 

my Beautiful Lyrics extention is buggy in windows 11 so i cant test it out 

Spotify for Windows (64 bit)
1.2.37.701.ge66eb7bc
Spicetify v2.36.11
xpui_2024-05-03_1714757530304_e66eb7b
cef_122.1.13+gde5b724+chromium-122.0.6261.130
Runtime: Chrome
Build System: CMake
