### ISSUE TITLE
Can't move Spotify window

### ISSUE THREAD

**Issue by tr330p** [sanoojes/better-bloom#40]
### Do you have the latest versions of Spicetify, Spotify and Better Bloom?

- [X] I'm using the latest versions of Spicetify, Spotify and Better Bloom

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Is your problem definitely caused by the theme?

- [X] I have checked the app behavior without the theme and it is different

### Environment & Computer Info

```Markdown
- Spotify version: 1.2.40.599.g606b7f29
- Installed from:Spotify site
- Spicetify version: v2.36.13
- Color scheme: -
- Extensions: - 
- Custom apps: -
- Better Bloom installation method: Spicetify Marketplace
```

### Description

Nothing much; I just can't move Spotify window to anywhere, maybe it's just a bug after Spicetify updated I've tried to disable theme; after disabling it, it function normally

**Comment by sanoojes** [comment]
soory for the issue caused i will address it rn !
