### ISSUE TITLE
Improvements on What's New page

### ISSUE THREAD

**Issue by kernelb00t** [sanoojes/better-bloom#5]
- Putting "Add to Library", "Download" and "More" buttons next to the Play button (saving space)
- Making "Play" button green (same styling overall with "Play" buttons in Home)
- Maybe sliding animations for "Download" and "More" on line hover (like on Home for "Play" buttons in item cards) ?
https://github.com/sanoojes/better-bloom/assets/68474172/3f46217e-e3c6-4e32-bd6c-2ce797a34c64

**Comment by sanoojes** [comment]
hey did you checkout the updated theme
