### ISSUE TITLE
[BUG] Queue misaligned in playback bar

### ISSUE THREAD

**Issue by znicuuu** [sanoojes/better-bloom#6]
The Queue Button misaligned is in playback bar.

![image](https://github.com/sanoojes/better-bloom/assets/73033465/26703309-bcb4-4652-9065-c330d24cba70)

Windows 11
Spotify für Windows (64 Bit)
1.2.37.701.ge66eb7bc
Spicetify v2.36.11
xpui_2024-05-03_1714757530304_e66eb7b
cef_122.1.13+gde5b724+chromium-122.0.6261.130
Runtime: Chrome
Build System: CMake

**Comment by sanoojes** [comment]
it is fixed now check new update

**Comment by sanoojes** [comment]
![image](https://github.com/sanoojes/better-bloom/assets/93819264/946c1331-86e6-4759-8f65-7edf096dc81b)

**Comment by znicuuu** [comment]
yup fixed :)
