### ISSUE TITLE
[BUG] The artist main page is really broken when scrolling down

### ISSUE THREAD

**Issue by MrMcNuggie** [sanoojes/better-bloom#7]
Whenever I go to an artist's main page it seems alright at first but when i scroll the banner image stays in place and it looks broken and janky

![Screenshot 2024-05-17 135002](https://github.com/sanoojes/better-bloom/assets/97690686/5560dc19-8e2e-4894-9da4-e6fce6afdb2d)

Im on the latest version of spicetify and spotify
Im not sure if this helps but i installed the theme from the spicetify marketplace

**Comment by sanoojes** [comment]
![image](https://github.com/sanoojes/better-bloom/assets/93819264/68aa616e-5f58-4a7f-bd9d-dcd7270ad170)
![image](https://github.com/sanoojes/better-bloom/assets/93819264/a3ab95a1-fcb4-4737-a687-9983d20b0122)

i think it is the issue with the spotify version can you try updating it should fix it 
it is working on newer version

**Comment by sanoojes** [comment]
@MrMcNuggie is the problem fixed sir ?

**Comment by sanoojes** [comment]
without proper context i cannot provide a fix the issue was solved in another commit so am closing this issue sir  @MrMcNuggie
