### ISSUE TITLE
the play/resume button is a white circle [BUG]

### ISSUE THREAD

**Issue by kamez104** [sanoojes/better-bloom#8]
As described in the title, the the play/resume button is a white circle. I'm on the latest version of Spotify and Spicetify, and I installed the theme through the Marketplace.
![image](https://github.com/sanoojes/better-bloom/assets/138945522/7030143e-55cf-41e5-bca0-c0a4177da10b)

**Comment by sanoojes** [comment]
can you give details of your spotify version try updating spicetify and spotify 

screenshot or copy paste the info

**Comment by sanoojes** [comment]
i cant reproduce the issue if the version, extensions used is not specified

**Comment by kamez104** [comment]
> can you give details of your spotify version try updating spicetify and spotify
Spotify for Windows (64 bit): 1.2.37.701.ge66eb7bc (latest from Spotify's website)
Spicetify: v2.36.11
Extensions: adblockify, Better Spotify Genres (the problem happens even with a fresh installation without any extensions)

**Comment by sanoojes** [comment]
sorry for the inconvinence.
i cant reproduce the problem. it might be a issue with spicetify or spotify installation

Try installing via using scripts after a fresh install of spotify and spicetify.

```powershell
# uninstall spicetify 
spicetify restore
rmdir -r -fo $env:APPDATA\spicetify
rmdir -r -fo $env:LOCALAPPDATA\spicetify
```

#### Windows (Powershell)

```powershell
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
iex "& { $(iwr -useb 'https://sanoojes.github.io/better-bloom/install/Better-Bloom.ps1') }"
```

> Tried reinstalling spicetify , spotify , marketplace , theme on windows 10, 11. 
![image](https://github.com/sanoojes/better-bloom/assets/93819264/7fa29c09-6a56-49ef-a57e-2683e5413310)
![image](https://github.com/sanoojes/better-bloom/assets/93819264/f984a6d7-1cce-4209-9335-8e7df55323b6)

**Comment by kamez104** [comment]
There's no point in reinstalling because I've already done it. It's not a big deal, I can live with it

**Comment by tajito** [comment]
Happening to me too, already tried reinstalling

Spotify for Windows (64 bit): 1.2.37.701.ge66eb7bc
Spicetify: v2.36.11
Extensions: Cat-Jam Synced, Beautiful Lyrics, No Tracking Links, Playlist Icons

**Comment by sanoojes** [comment]
> Happening to me too, already tried reinstalling
> 
> Spotify for Windows (64 bit): 1.2.37.701.ge66eb7bc Spicetify: v2.36.11 Extensions: Cat-Jam Synced, Beautiful Lyrics, No Tracking Links, Playlist Icons

sorry i dont know whats the issue i will try fixs for that

**Comment by sanoojes** [comment]
i will try to add -webkit-mask for mask-image compatibility sometimes it should fix the issue

**Comment by tajito** [comment]
> i will try to add -webkit-mask for mask-image compatibility sometimes it should fix the issue

nope ;_;
![image](https://github.com/sanoojes/better-bloom/assets/113896276/3518a0d7-dd96-4751-bcb6-606cb937cbe1)

**Comment by sanoojes** [comment]
> > i will try to add -webkit-mask for mask-image compatibility sometimes it should fix the issue
> 
> nope ;_; ![image](https://private-user-images.githubusercontent.com/113896276/331883310-3518a0d7-dd96-4751-bcb6-606cb937cbe1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxMzM3NzQsIm5iZiI6MTcxNjEzMzQ3NCwicGF0aCI6Ii8xMTM4OTYyNzYvMzMxODgzMzEwLTM1MThhMGQ3LWRkOTYtNDc1MS1iY2I2LTYwNmNiOTM3Y2JlMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxOVQxNTQ0MzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZGEyMWUzMjRmNmZiMDQ1NTU3MzJjYzIyZWFmYTAzOTM2NWI4ZWIyMmU1ZjljNGNiNWQyYjE0YmM5N2ZiYjc1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8d_WQubpQKiby--cai2RptjAhb3g-FOSfR-JnL0jC_s)

soory my bad i will try other fixes now

**Comment by sanoojes** [comment]
@tajito @kamez104 
hey can you check out the new update i removed the inline svg and add the play button image with scripts

**Comment by tajito** [comment]
> @tajito @kamez104 hey can you check out the new update i removed the inline svg and add the play button image with scripts

fixed! tysm :D

**Comment by sanoojes** [comment]
ok !

**Comment by kamez104** [comment]
fixed, tysm :D
