### ISSUE TITLE
Merged Window Controls on MacOS

### ISSUE THREAD

**Issue by AlexanderDotH** [sanoojes/better-bloom#9]
### Do you have the latest versions of Spicetify, Spotify and Better Bloom?

- [X] I'm using the latest versions of Spicetify, Spotify and Better Bloom

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Is your problem definitely caused by the theme?

- [X] I have checked the app behavior without the theme and it is different

### Environment & Computer Info

```Markdown
- Spotify version: Mac OS Latest
- Installed from: (Windows Store, Spotify site, Flatpak, etc)
- Spicetify version: spicetify v2.36.11
- Color scheme: All
- Extensions: -
- Custom apps: Marketplace
- Better Bloom installation method: (Spicetify Marketplace/PowerShell script/Bash script/Manual)
```

### Description

Window decorations are merged with the spotify content on macos which results an undraggable window

### Screenshots

<img width="1982" alt="image" src="https://github.com/sanoojes/better-bloom/assets/20642291/2f294867-82c3-4905-9ccc-a71f63c4a56d">
<img width="209" alt="image" src="https://github.com/sanoojes/better-bloom/assets/20642291/e1a248bb-9056-4cb7-8c38-bf2d564d58dc">

**Comment by sanoojes** [comment]
ohh soory for the issue i dont have access to a mac i will try to fix it

**Comment by AlexanderDotH** [comment]
No Problem, I can test it for you If you want.   Add me on discord. Tag: alexdoth

**Comment by sanoojes** [comment]
Thankss ! it would be nice if you can do it for me i will tag you on discord

**Comment by sanoojes** [comment]
can you check the new update i think it should fix the issue
